apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-crud-app
  labels:
    app: nodejs-crud-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-container
        image: sonbarse17/nodejs-crud-app
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mongo-service"
